name: repaint-bar
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - ipykernel
  - numpy
  - scipy
  - matplotlib
  - pillow
  - opencv
  - pandas
  - tqdm
  - pyyaml
